--enable-tap-tests

diff --git a/openindiana/Vagrantfile b/openindiana/Vagrantfile
--- a/openindiana/Vagrantfile
+++ b/openindiana/Vagrantfile
@@ -12,13 +12,20 @@ Vagrant.configure("2") do |config|
      pkg install gcc-10 gdb flex bison autoconf ccache git vim screen
   SHELL
 
-  # get a source tree and some scripts to start things off
+  # things to run as vagrant user
   $setup_tree = <<-SHELL
+    # pull down the source tree
     git clone https://github.com/postgres/postgres.git
+
+    # set up lazy scripts so I don't have to remember the options
     cd postgres
     echo './configure --prefix=$HOME/install --enable-cassert --enable-debug CC="ccache gcc"' > reconfigure.sh
     echo 'gmake -s clean && gmake -s -j4 && gmake -s install && gmake -s check' > rebuild.sh
     chmod +x reconfigure.sh rebuild.sh
+
+    # warm up ccache by building and installing (it's not a provisioning
+    # failure if this step fails, though)
+    ./reconfigure.sh && ./rebuild.sh && gmake -s check || true
   SHELL
   config.vm.provision "shell", inline: $setup_tree, privileged: false
 
