Might as well build during provisioning.
A nice warmed-up ccache.

diff --git a/netbsd9/Vagrantfile b/netbsd9/Vagrantfile
--- a/netbsd9/Vagrantfile
+++ b/netbsd9/Vagrantfile
@@ -9,7 +9,6 @@ Vagrant.configure("2") do |config|
   config.ssh.forward_agent = true
 
   # install the packages we need and configure the crusty old sysv semaphores
-  # so that postgresql's make check doesn't fail
   config.vm.provision "shell", inline: <<-SHELL
     pkgin -y install gmake git flex bison ccache readline screen mozilla-rootcerts
     mozilla-rootcerts install
@@ -19,13 +18,20 @@ Vagrant.configure("2") do |config|
     sysctl -w kern.ipc.semmns=256
   SHELL
 
-  # get a source tree and some scripts to start things off
+  # things to run as vagrant user
   $setup_tree = <<-SHELL
+    # pull down the source tree
     git clone https://github.com/postgres/postgres.git
+
+    # set up lazy scripts so I don't have to remember the options
     cd postgres
     echo './configure --prefix=$HOME/install --enable-cassert --enable-debug CC="ccache cc"' > reconfigure.sh
-    echo 'gmake -s clean && gmake -s -j4 && gmake -s install && gmake -s check' > rebuild.sh
+    echo 'gmake -s clean && gmake -s -j4 && gmake -s install' > rebuild.sh
     chmod +x reconfigure.sh rebuild.sh
+
+    # warm up ccache by building and installing (it's not a provisioning
+    # failure if this step fails, though)
+    ./reconfigure.sh && ./rebuild.sh && gmake -s check || true
   SHELL
   config.vm.provision "shell", inline: $setup_tree, privileged: false
 
